### ISSUE TITLE
Label Inconsistency with elementary OS default Indicator

### ISSUE THREAD

**Issue by reorr** [maze-n/indicator-daynight#1]
Hi there, Mazen!

Nice work you have here.
I think for the label case, it should follow the elementary OS indicator label to provide more consistent experience.
elementary OS use title case for label in indicator and "h4" class in switch label if it's a primary action.
I have attached the example bellow.

Current state:
![screenshot](https://user-images.githubusercontent.com/10528000/71505383-93a9fb80-28af-11ea-9abc-f3d177c4c7da.png)

Example indicator from elementary OS default:
![wifi](https://user-images.githubusercontent.com/10528000/71505414-ad4b4300-28af-11ea-8951-d4f2220d499f.png)
![notification](https://user-images.githubusercontent.com/10528000/71505415-ade3d980-28af-11ea-80a3-c58fd1a27935.png)
![bluetooth](https://user-images.githubusercontent.com/10528000/71505416-ae7c7000-28af-11ea-8b6d-8f2a446a15a9.png)
![battery](https://user-images.githubusercontent.com/10528000/71505418-afad9d00-28af-11ea-9152-56dc75650203.png)

**Comment by maze-n** [comment]
Hello..!!

I really appreciate your response, I mean really your comment was in very much detail, so much that I barely had to do anything, and I guess the issue is now resolved ...

And as always feedback are always welcome.

**Comment by reorr** [comment]
Thank you!

I will close this issue now.
